### ISSUE TITLE
Messed up projection when output routes are put in a feature dataset

### ISSUE THREAD

**Issue by mmorang** [Esri/public-transit-tools#107]
Reported by @Holisticnature using a feature dataset with Denver state plan coordinates

**Comment by Holisticnature** [comment]
Specifically, in ArcMap 10.3+ it seems that the feature data set will override the spatial reference we want to use with CreateFeatureClass. As a result the output data was in the wrong location.

**Comment by mmorang** [comment]
This is actually an issue in several of my tools.  Working on a fix.

**Comment by mmorang** [comment]
My latest code merge should resolve the problem.  Please let me know if you encounter any further problems.
I will update the AGOL downloadable versions momentarily.

**Comment by Holisticnature** [comment]
Hi Melinda, 
Do the shared function also require updating? I did not see the changes you made (projectAs) in this. 
https://github.com/Esri/public-transit-tools/blob/a800f23a6d9d7961f51b93118ba3342c51cb7010/better-bus-buffers/BBB_SharedFunctions.py

David

**Comment by mmorang** [comment]
I did make a change in that file.  https://github.com/Esri/public-transit-tools/pull/110/files

**Comment by mmorang** [comment]
The link you shared isn't the master branch.

**Comment by Holisticnature** [comment]
Understood. Thanks.
