### ISSUE TITLE
Wrapping Tools in Functions

### ISSUE THREAD

**Issue by d-wasserman** [Esri/public-transit-tools#114]
Is there any particular reason why the tools analysis functions are not wrapped in functions with parameters? One challenge I have had is that sometimes it makes sense to use Python with these tools and that is often made difficult because the functionality is not wrapped inside of a functions. 
The benefits of doing this are the following:

- Enables tool import into other tools outside of this library

- Makes it easier to build off the tools

- Provides a way to edit inputs without going through the GUI

I am willing to help with this if this is a big ask. The general pattern I used for [my tools looks like this](https://github.com/Holisticnature/proximity-analysis/blob/master/Scripts/ChainedNearAnalysis.py): 

`# Main Function
def chained_near_analysis(in_fc, near_features, search_radius=None, location=False, angle=False,fid=False,
                          method="PLANAR"):

....

if __name__ == '__main__':

    # Define input parameters

    input_features = arcpy.GetParameterAsText(0)

    near_features = str(arcpy.GetParameterAsText(1)).split(";")

    search_radius = arcpy.GetParameter(2)

    location = arcpy.GetParameter(3)

    angle = arcpy.GetParameter(4)

    fid = arcpy.GetParameter(5)

    method = arcpy.GetParameterAsText(6)

    chained_near_analysis(input_features, near_features, search_radius, location, angle,fid, method)`

This isolates the function from the GetParameter functions which require typically some interaction from a GUI. Do you have any concerns with this approach?

**Comment by mmorang** [comment]
I agree that this would be helpful.  The main reason is that I wrote most of my tools a long time ago as simple script tools, and I've learned a lot more about python since then.  I would like to rewrite them into class-based object-oriented structures at some point, but since they're basically working as is it's a low priority to do a complete refactoring.

Could you specify which tool(s) or scripts you are most concerned with?

**Comment by Holisticnature** [comment]
I think this is a low hanging fruit request that might help with a future refactor down the line. 

I would prioritize the higher level scripts first (accessibility tools for example). I think Add GTFS to NDS and BBB are highest priority for this type of change. BBB has this already implemented to some extent (`[runTool is fine, but I wish it was more descriptive)](https://github.com/Esri/public-transit-tools/blob/master/better-bus-buffers/BBB_CountTripsAtPoints.py)`.

**Comment by mmorang** [comment]
Is there a reason, when using python, that you need to call the tools as functions rather than calling them as GP tools?  Because the latter ought to work, if you've successfully imported the toolbox.

**Comment by Holisticnature** [comment]
I think my concern is you are locked in to using the toolbox. It also does [not feel very pythonic](https://pro.arcgis.com/en/pro-app/arcpy/functions/importtoolbox.htm). I have not had a lot of great experiences trying to work with imported toolboxes. Even something like importing the script and calling runTool would be preferable. It is another layer of complexity I think would be annoying to deal with.

**Comment by mmorang** [comment]
Yeah, fair enough.

**Comment by d-wasserman** [comment]
It seems many functions have been added the library, and thus much of the functionality is modular now. I actually needed this so thank you for making those changes.

**Comment by mmorang** [comment]
Add GTFS is going to be deprecated soon, so I will not be making any changes there.  Are the changes I've already made to BetterBusBuffers sufficient for your needs?  Can I close this issue?

**Comment by d-wasserman** [comment]
I think they should be given more readable names besides "main()", but most of the Transit Analysis Tools have been wrapped.
To clarify the transit analysis tools will not be deprecated? Just Add GTFS to NDS?

**Comment by mmorang** [comment]
The transit analysis tools will not be deprecated.  They have been re-implemented as a python toolbox in a similar way to BetterBusBuffers (runTool()) in [this branch](https://github.com/Esri/public-transit-tools/tree/DeprecateAddGTFS), which will be merged as soon as Pro 2.4 is released.

**Comment by mmorang** [comment]
(Sorry, forgot about that detail)

**Comment by d-wasserman** [comment]
I still think runTool is not very pythonic, but acceptable. Thank you for incorporating this feedback, it actually saved me on a project.
