### ISSUE TITLE
Make Add GTFS to a Network Dataset work in ArcGIS Pro

### ISSUE THREAD

**Issue by mmorang** [Esri/public-transit-tools#117]
Add GTFS to a Network Dataset is not supported in Pro because it uses a "custom evaluator" built in ArcObjects, and Pro's SDK does not allow you to create or use a custom evaluator.  So unfortunately, there is just no way to make this work at this time.

However, I have been hearing more requests for this functionality, and hearing from users is a good way for me to advocate for support internally here at Esri.  If you would like to see the Add GTFS to a Network Dataset tool or equivalent functionality available in ArcGIS Pro, please up-vote this issue and/or leave a comment explaining your use case.

**Comment by laurentwww** [comment]
As we are now using Pro version in our organization, that will be very helpful and more powerful working in Pro.
Many thanks.

**Comment by Holisticnature** [comment]
I second this. Network analysis in pro is incredibly fast. It opens up degrees of temporal-spatial analysis we honestly could not do with ArcMap.

**Comment by mmorang** [comment]
Great news, everyone!  ArcGIS Pro 2.4 (releasing this summer) will natively support public transit in Network Analyst.  There will be no need for a separate download, so the Add GTFS to a Network Dataset tool will be deprecated.  I'll make a more detailed announcement here after Pro 2.4 is released with some information about how you can get started with it.

**Comment by mmorang** [comment]
ArcGIS Pro 2.4 was released today.  Learn more about the new public transit functionality in Network Analyst here: https://pro.arcgis.com/en/pro-app/help/analysis/networks/network-analysis-with-public-transit-data.htm
