### ISSUE TITLE
Unspecified Error with Display GTFS Route Shapes

### ISSUE THREAD

**Issue by ChristophColombo** [Esri/public-transit-tools#118]
I've been using the Display GTFS toolbox without issue for the past couple years, but it has suddenly started throwing an error.  Unfortunately, there's absolutely no information on what the error is.  I see the red warning icon on the GTFS Directory field when I first open the tool (with no alt/hover text), and when I enter a file path and run it, I get an empty error message (see attached images).  I've already tried downloading the latest files, but that doesn't seem to have changed anything.

![image](https://user-images.githubusercontent.com/23487923/37850729-4575d7e6-2eaa-11e8-9dfd-507aac56c809.png)

![image](https://user-images.githubusercontent.com/23487923/37850680-285fcb80-2eaa-11e8-86b3-ad51b24392d1.png)

**Comment by mmorang** [comment]
That's a very frustrating error!

Did you install Anaconda, by any chance, or make any other changes to python?  Sometimes this causes ArcGIS's version of python to get messed up, and then script tools in general don't work.

To test if python is working in ArcMap:
- Open the python window.
- Type `import arcpy`.  If that throws some kind of error, then python is messed up, and you should either reinstall ArcMap, or call [Esri Support](https://support.esri.com/en) (or whatever your local distributor is) to get help fixing it.

Try that, and if that's not the problem, let me know, and we'll try something else.

**Comment by ChristophColombo** [comment]
Aha, that's probably the issue.  I did recently install Anaconda, and running the import arcpy command causes an app crash.  I'll try reinstalling ArcGIS.  Thanks!

**Comment by mmorang** [comment]
Feel free to re-open this issue if reinstalling doesn't solve the problem.  Good luck!
