### ISSUE TITLE
Add route_id in directions windows (Route analysis)

### ISSUE THREAD

**Issue by SMackeySTLevis** [Esri/public-transit-tools#125]
Hello,

First, I wanted to thank Melinda Morang for the hard work in creating the tools helping us to merge the GTFS files and ArcMap. I am a new transit planner in the province of Quebec since the last two months and I have had a little bit of time this summer to build a complete network of the region, and I now have added our transit info which makes it very interesting to model accessibility and origin/destination information.

While exploring the different features of the tools, I tried the Route analysis between two points, adding the directions to the Network so that I would know which streets and which bus route were taken. I then realized that the support for the bus routes was not implemented at this moment (it just says Bus at shown below).

![directions](https://user-images.githubusercontent.com/42678010/44596495-610f6080-a79a-11e8-9d58-5ffa34db4c95.png)

I was wondering if it was a possibility that the feature could be added in the future. I realize that the TransitLines feature class only shows one line between the two stops even though there are multiple bus routes using that particular line. But I wonder if, using the time that the user boards the bus at the first stop (i.e. stop 990094 at 08:11), it could find in the schedule what bus line it should be.

I also found out that there is no showing of the wait time at the stop. It only gets added to the time that is shown being in the bus. Is that something that could be implemented?

Thanks again for the tools, I'm sure that I will have a lot of fun in the coming weeks creating useful data for our future network redesign!

Sebastien

**Comment by mmorang** [comment]
Hello Sebastien.  I'm glad my tools have been useful for you!

To retrieve a list of the transit stops, lines, and wait times that were used in the Route, you can use the [Copy Traversed Source Features (with Transit)](https://github.com/Esri/public-transit-tools/blob/master/add-GTFS-to-a-network-dataset/UsersGuide_TransitAnalysisTools.md#CopyTraversed) tool located in the Transit Analysis Tools toolbox that comes with the Add GTFS to a Network Dataset download.  This doesn't produce directions text like the screenshot above, but it will show you which lines were used in a table format.  Would this suit your needs?

**Comment by mmorang** [comment]
The Route solver does not give you the option to specify an end time.  However, you can use the Closest Facility solver with just one Incident and one Facility, and this will accomplish the same thing and DOES allow you to specify either a start or an end time.

**Comment by SMackeySTLevis** [comment]
That seems to work pretty fine, the only thing is that it tries to arrive the closest possible to 9:00 AM, so it makes the user get out of the bus a few stops early and then walk to arrive to its destination... That's funny! 

Though that's ok for me since I only need the boarding stop and the bus line that the user is on, not the exiting stop or the total time of travel.

**Comment by mmorang** [comment]
Great!  I'm glad I was able to solve the problem (without actually having to do anything).
