### ISSUE TITLE
Get Network EIDs error 

### ISSUE THREAD

**Issue by gracjanm** [Esri/public-transit-tools#130]
Hello, 
I have a question about an error that I can not find an answer anywhere. After performing the analyzes described in the example, I reach the last element, that is adding data to Network EIDs. In previous analyzes, no errors appear, everything goes normally only when adding data an error pops up? What could be the reason?
![s](https://user-images.githubusercontent.com/44155827/46935125-81e98900-d05a-11e8-9545-d3409d8575e3.png)

**Comment by mmorang** [comment]
Did you ever resolve this issue?

**Comment by ukusun** [comment]
I met the same problem。 I've tried many ways, but failed.

**Comment by mmorang** [comment]
Have you tried turning off background geoprocessing so that the tool runs in the foreground?  It shouldn't make a difference unless you have the 64-bit background geoprocessing extension installed, but it's worth a try.

**Comment by ukusun** [comment]
I've just turned off background geoprocessing button and tried to use get EID tools again, but it failed to aquire extension license too.
Could you give me a remotely help by QQ?

**Comment by mmorang** [comment]
I never found a solution to this problem.  However, the Add GTFS to a Network Dataset toolset will be deprecated as soon as ArcGIS Pro 2.4 is released (this summer) because Pro 2.4 will natively support network analysis with public transit data.

I do not plan to address this issue, so I'm closing it.
