### ISSUE TITLE
GetNetworkEIDs tool fails when ArcPy is used.

### ISSUE THREAD

**Issue by tstrych** [Esri/public-transit-tools#134]
Hello, 
I am trying to build stand alone Arcpy script. The result of this script should be Network Dataset.
The path to network dataset is not accepted.  However the tool in ArcMap works well.

#### To reproduce this error.
Prepare Network Dataset for Get EIDs tool.
I run these commands to python window in ArcMap

```
arcpy.ImportToolbox('C:/Program Files (x86)/ArcGIS/Desktop10.6/ArcToolbox/Toolboxes/Add GTFS to network dataset.tbx')

arcpy.GetNetworkEIDs_transit('C:/geodatabases/fGDB.gdb/fd/Transit_Network_ND') # path to my Network Dataset
```

#### And end up with this error:
```
Runtime error  Traceback (most recent call last):   File "<string>", line 1, in <module>   
File "c:\program files (x86)\arcgis\desktop10.6\ArcToolbox\Toolboxes\Add GTFS to network dataset.tbx", line 82, in GetNetworkEIDs    
ExecuteError: Error obtaining network EIDs. Index was outside the bounds of the array.  
Failed to execute (GetNetworkEIDs).
```
This error is exactly matching with error from my stand alone script.

#### I tried same command with back slah notation.
`arcpy.GetNetworkEIDs_transit('C:\geodatabases\fGDB.gdb\fd\Transit_Network_ND') `
And I run into the slightly different error. 
```
Runtime error  Traceback (most recent call last):   File "<string>", line 1, in <module>  
File "c:\program files (x86)\arcgis\desktop10.6\ArcToolbox\Toolboxes\Add GTFS to network dataset.tbx", line 82, in GetNetworkEIDs    
ExecuteError: Failed to execute. Parameters are not valid. The feature dataset where your network dataset resides does not have a feature class called 'TransitLines'. 
Please use a valid network dataset. Failed to execute (GetNetworkEIDs). 
```

As you can see I am using ArcGIS 10.6 and Python 2.7.14 

#### Then I run exactly same tool in desktop and everything goes well. 
![Screenshot from 2019-03-11 19-18-15](https://user-images.githubusercontent.com/19147547/54147458-814ef600-4432-11e9-987c-5c8a752d601d.png)

#### I was looking in repository and I found same issue resolved by PR.
referenced [closed issue](https://github.com/Esri/public-transit-tools/issues/80)
referenced [PR](https://github.com/Esri/public-transit-tools/pull/81/files)

If you need any additional info do not hesitate to let me know.

**Comment by mmorang** [comment]
Try using python's "r" notation, which passes in the string exactly as written:
`arcpy.GetNetworkEIDs_transit(r'C:/geodatabases/fGDB.gdb/fd/Transit_Network_ND')`

Does that help?

**Comment by tstrych** [comment]
Tried, but nothing changed. Same result.

**Comment by mmorang** [comment]
Maybe a dumb question, but does the TransitLines feature class actually exist in your feature dataset?

**Comment by tstrych** [comment]
Yes I have. 
![Screenshot from 2019-03-11 20-49-20](https://user-images.githubusercontent.com/19147547/54153179-3a1b3200-443f-11e9-9044-9dd6950e92fc.png)

**Comment by tstrych** [comment]
I can send you an e-mail with my arcpy script, maybe it can helps. And anyway thanks for your really quick reaction.

**Comment by mmorang** [comment]
Calling the tool on an existing network dataset is working fine for me, so this is a bit hard to diagnose.

Your comments imply that your script is creating the network dataset and doing some other stuff prior to running the Get EIDs tool.  Can you create a script that only calls the Get EIDs tool on an existing network dataset and does nothing else?  Does that succeed?  If so, there must be some problem with the larger workflow going on in your script.  If you share your script, I could take a look.

**Comment by tstrych** [comment]
I sent the script to @mmorang she helps me, also gives me some tips with my script,  now it's perfectly working thank you very much.

Problem was in paths. I was using `a = b + "/" + c` system and I should be more pythonic and I should use `a = os.path.join(b,c)`

**Comment by mmorang** [comment]
Glad that worked!!
