### ISSUE TITLE
Prepare Time Lapse Polygons / Network Analyst Service Area - +24:00 time

### ISSUE THREAD

**Issue by gjhanton** [Esri/public-transit-tools#176]
Hey, hoping for a little advice / clarity on how the Public Transit Tool evaluator handles GTFS stop times that begin after midnight, and are considered to be run within the previous day's transit schedule (i.e. night services +24:00). Example below (for 1:05am) of how our GTFS for NSW has stops times listed for services that either commence or continue to run past midnight:

"23.AA55.1-19T-8-sj2-1.2.H","**25:05:00**","**25:05:00**","216712","8","","0","0","42140.91","1",""

I'm creating 30 minute public transport catchments with the Service Area tool, and comparing against the Prepare Time Lapse Polygons tool. The results are similar, however I'm unsure that the catchments are accurately reflecting the services running - when comparing against a Trip Planner visible to the public. One approach was to modify the stop_times.txt from the GTFS, for the periods I'm looking at (depart at 12am, depart at 1am), i.e. 25:00 becomes 01:00. Is this feasable? Any other suggestions on how to handle these time formats? I'm relatively new to GTFS / creating Service Area / catchments. Thanks!

**Comment by mmorang** [comment]
Sure, happy to help.

As long as your GTFS is valid and the stop times follow the GTFS spec (including where the stop times are > 24:00), then Esri's tools will handle them correctly without your needing to do anything.  The [GTFS To Public Transit Data Model](https://pro.arcgis.com/en/pro-app/latest/tool-reference/public-transit/gtfs-to-public-transit-data-model.htm) tool parses the GTFS and converts it into our public transit data model, and it handles these situations seamlessly.

When you actually solve an analysis, our Public Transit evaluator will look at the schedules stored in our data model tables and determine what services are running for the date and time when the network is being queried.  When the analysis spans midnight (like if the pedestrian starts traveling at 11:55pm), the evaluator will account for all service still running from the day the analysis starts and added service that starts running on the next day shortly after midnight.  If the analysis starts in the early morning hours, it will account for leftover services running from the previous day.  We have tested all this thoroughly, so it should be doing the right thing.

Hope this helps!

**Comment by gjhanton** [comment]
Hey Melinda, thanks for the clarification / additional info, and quick response! I'll pass this onto the team I'm working with. Will follow-up if I have any other questions. Many thanks!

**Comment by mmorang** [comment]
You're welcome!  I'm going to close this issue since it seems like your question has been answered and there's nothing to fix, but feel free to reopen if you have further questions, or open another one.
