### ISSUE TITLE
Create a blank stop_time removal utility

### ISSUE THREAD

**Issue by mmorang** [Esri/public-transit-tools#25]
Many GTFS datasets contain blank values for arrival_time and departure_time in stop_times.txt.  This can be intentional (datasets using time points) or by mistake.  Because no exact values are present, these datasets cannot be used in my tools.  It is possible to interpolate stop_time values as a reasonable estimate, but interpolation needs to be done with care because the analysis results based on this interpolation could produce incorrect or misleading results.

**Comment by Holisticnature** [comment]
I think as long as the interpolation provides some degree of error (either a count of stop times filled or something more complex like the results of a [Kriging interpolations prediction error](http://gis.stackexchange.com/questions/146699/unit-of-measurement-from-standard-error-prediction-map)), any interpolation would be good. I think this would be a very helpful change in the tools.

**Comment by mmorang** [comment]
I have uploaded a utility for doing a simple interpolation of blank stop time values.  It just distributes the blank times even between surrounding time points without regard to distance between stops.  Eventually, I'd like to add some more advanced logic using network distance, but this is a start.
