### ISSUE TITLE
Stop names

### ISSUE THREAD

**Issue by knuaas** [Esri/public-transit-tools#49]
Adding stop_names when running Generate GTFS Shapes with ArcGIS Online or Network Analyst would be very welcome. Would it be possible to add such functionality?

**Comment by mmorang** [comment]
That shouldn't be too hard to add.  How critical is this to your workflow? In other words, how badly do you want this, or how soon do you need it?

**Comment by knuaas** [comment]
It's not critical for my workflow. I use workaround where I import stops.txt to Google Earth, export to .KML and then run the KML to layer toolbox in ArcMap.
It would be more a time-saver in the long run but not something that I really need.

**Comment by mmorang** [comment]
As a more efficient workaround, you could just add stops.txt to ArcMap using Add XY Data and use a join by stop_id to transfer the stop_name over to the Generate GTFS Shapes stops layer.

But I an easily add this functionality to the tool when I have a little free time.

**Comment by mmorang** [comment]
This functionality has been added to the new version of this tool I am adding in core ArcGIS Pro.  All the fields from stops.txt will be included.

Because I'm putting the tool in the core software, I will not make any changes to the existing prototype tool.
