### ISSUE TITLE
GeoEvent Adaptor for GTFS realtime data

### ISSUE THREAD

**Issue by brandonflessner** [Esri/public-transit-tools#6]
It would be great to have a GeoEvent Adaptor for GTFS realtime data. I've looked around but have not found anything.

**Comment by mmorang** [comment]
Hello brandonflessner.

We have added a script that will hopefully help you with this.  Check it out in the send-GTFS-rt-to-GeoEvent folder.  Please let us know if this doesn't give you enough to work with.
