### ISSUE TITLE
Make a tool to assess schedule adherence 

### ISSUE THREAD

**Issue by mmorang** [Esri/public-transit-tools#65]
Collect gtfs-rt over a period of time and compare it with the schedule data to highlight areas where the schedule needs work (and possibly export a corrected schedule back out to GTFS).  Let's close the feedback loop!

**Do you want a tool like this?**
If you work for a transit agency and are interested in studying schedule adherence, I would love to talk to you.  Please contact me.

**Comment by mmorang** [comment]
From some preliminary research, it looks like the Vehicle Positions portion of the GTFS-rt feeds would be the most relevant, if they can be recorded over time.  It contains far more information than I initially assumed, though it's not clear how many agencies actually populate all that information.

For accessing the feeds through python, this will be helpful: https://github.com/google/gtfs-realtime-bindings/tree/master/python

**Comment by mmorang** [comment]
For future reference, for messing around with installing python packages:

- To download the VirtualEnv package that works with Python 2.7, get the latest .tar.gz  file from  https://pypi.python.org/pypi/virtualenv and unzip using 7-zip.
- Then to create a new virtualenv called “env” in a folder called “test” with access to global site packages (in case you need to use arcpy): <Path to python.exe> "E:\PyPlay\virtualenv-15.1.0\virtualenv.py" test\env –system-site-packages
- Always remember to activate the virtualenv before using it. test\env\scripts\activate.bat
- Then you can run pip to get the package in your virtualenv

**Comment by Holisticnature** [comment]
As previously discussed, I could see a use case for this. As you noted, the information inside of a real time GTFS feed is potentially very dense (schedule adherence and other info).  I think the historical component (over a week or month) could be good for speed/reliability analysis.

**Comment by mmorang** [comment]
Closing this issue.  Cory Whittaker, a solution engineer for Esri, has implemented a tool for this in ArcGIS Velocity.  If you're interested in that, reach out to transit@esri.com to learn more.
