### ISSUE TITLE
Make a better installer

### ISSUE THREAD

**Issue by mmorang** [Esri/public-transit-tools#66]
@matt3274  says he knows of a better way to register transitevaluator.dll with ArcMap.  This is a real problem for a lot of users.

**Comment by Holisticnature** [comment]
I have also had issues with this DLL. If there is a better way, it would be good to explore that.

**Comment by mmorang** [comment]
This is being worked on.  No guarantees, but I'm hoping for a working installer in the next month or two.

**Comment by mmorang** [comment]
At long last, an official installer for Add GTFS to a Network Dataset! This should resolve most of the extensive problems people have with registering the transit evaluator.

Note that only the pre-compiled installer code is included here. The compiled installer will be available from ArcGIS Online for download, and that's how you actually install the tools. (Will be added shortly)
