### ISSUE TITLE
Status Update on ArcGIS Pro Integration

### ISSUE THREAD

**Issue by Holisticnature** [Esri/public-transit-tools#67]
Is there any status update on when and how network analyst integration in ArcGIS Pro will happen? 

I saw that the .NET framework API for Pro was released, and so I was curious about what the bottlenecks on this integration are?

**Comment by mmorang** [comment]
I presume you are talking about the Add GTFS to a Network Dataset tool and not Network Analyst in general.  Network Analyst in general is already supported in ArcGIS Pro.  Unfortunately, there are currently no plans to support the Add GTFS to a Network Dataset tool in Pro.  Add GTFS to a Network Dataset uses a custom evaluator to read the transit schedules and use them during the network solve process.  Pro does not provide a way to create or use a custom evaluator.  It's in our current agenda to research customers who are using custom evaluators for various things so we can find out how to support those customers in Pro, but as of right now, it does not seem likely that we'll support custom evaluators as they are currently implemented in 10.x.  So, Add GTFS to a Network Dataset remains a 10.x-only tool.

**Comment by Holisticnature** [comment]
Thanks for the update Melinda. If there are other approaches to integrate GTFS into a network dataset I think it would be valuable to explore them. In order to do integrated accessibility analysis in Pro for the main  modes considered as part of many planning studies it would be critical to be able to do isochrones for transit. Otherwise other libraries become much more suited for this type of analysis in the long term.
