### ISSUE TITLE
GetEIDs fails validation if input is a network dataset layer

### ISSUE THREAD

**Issue by mmorang** [Esri/public-transit-tools#80]
It throws "The feature dataset where your network dataset resides does not have a feature class called 'TransitLines'. Please use a valid network dataset."  It's getting confused because when the input is a network dataset layer rather than the catalog path, it isn't correctly finding the feature dataset.  Need special handling for this case.

**Comment by PPaulsonOregonDOT** [comment]
Is this related to the message (below), that I get when I try to run GET EID's?
Messages
Executing: GetNetworkEIDs C:\ProgramData\GTFStoNetworkTest.gdb\GTFStoNetworkTest\GTFStoNetworkTest_ND
Start Time: Thu Sep 14 14:19:43 2017
Running script GetNetworkEIDs...
Retrieving EIDs from network dataset...
(This step might take a while.)
Error obtaining network EIDs.
The system cannot find the path specified.
Completed script GetNetworkEIDs...
Failed to execute (GetNetworkEIDs).
Failed at Thu Sep 14 14:19:44 2017 (Elapsed Time: 0.92 seconds)

**Comment by mmorang** [comment]
No.  The issue here occurs only if the input is a layer in the map and not a catalog path to a network dataset.  However, I'm also seeing the issue you mentioned, and I'm not quite sure why.  What version of ArcMap are you using?

**Comment by PPaulsonOregonDOT** [comment]
Currently using 10.2.2.

**Comment by mmorang** [comment]
Have you ever been able to successfully run this tool?  For example, does it work on a different network dataset, did it work with a different version of ArcMap or a different version of the Add GTFS toolbox?

**Comment by PPaulsonOregonDOT** [comment]
I have not been able to successfully run this tool.  I've only used the most up-to-date GTFS toolbox, with the only network dataset and version of ArcMap that I have access to.

**Comment by mmorang** [comment]
Okay, thanks.  I'll get it figured out.

**Comment by mmorang** [comment]
@PPaulsonOregonDOT: For your issue, it's because you have to first build GetEIDs.exe from the GetEIDs stuff included here.  I'm not sure how much luck you'll have with that unless you're already familiar with building ArcObjects executables.  If you're just looking for something to use out of the box, download the ready-to-use version of these tools from here: http://www.arcgis.com/home/item.html?id=0fa52a75d9ba4abcad6b88bb6285fae1

For my own part, I was just having a moment of exceptional stupidity when testing my update to the tool and forgetting that I needed to copy the file to a place where I already have GetEIDs built...however, it served me well because otherwise I would not have realized that this was the answer to your problem.
