### ISSUE TITLE
Errors with all tools

### ISSUE THREAD

**Issue by j7hanson** [Esri/public-transit-tools#83]
Hi

Can these tools run in ArcGIS 10.4.1? 

I have an ImportError: C extenstion: no module named builtins not built. 

Thanks

**Comment by mmorang** [comment]
Yes, these tools work in 10.4.1.  Can you specify which tool is causing the problem and where exactly you see the error?

**Comment by j7hanson** [comment]
I'm having various issues with each of the tools, specifically DisplayGTFSRouteShapes. My zipped GTFS folder contains the appropriate Shapes folder. 

Here is the longer version of the error.
Traceback (most recent call last):
  File "C:\Users\j\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\display-GTFS-in-ArcGIS\scripts\LaunchDisplayGTFSRouteShapes.py", line 46, in <module>
    import DisplayGTFSRouteShapes as disp
  File "C:\Users\j\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\display-GTFS-in-ArcGIS\scripts\DisplayGTFSRouteShapes.py", line 27, in <module>
    import pandas as pd
  File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\__init__.py", line 13, in <module>
    "extensions first.".format(module))
ImportError: C extension: No module named builtins not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.


Thanks for the quick reply!

**Comment by mmorang** [comment]
Try the following:
1) Open ArcMap
2) Open the [python window](http://desktop.arcgis.com/en/arcmap/latest/analyze/executing-tools/what-is-the-python-window-.htm#ESRI_SECTION1_276E292B80D2439DB179ED9B3B6B63E7)
3) In the python window, type "import pandas" (no quotes).  Does that work?
4) Also try typing "import sqlite3".  Does that work?

The pandas module started getting installed with ArcMap in 10.4, so this _should_ be working.  The sqlite3 module has been included forever, so definitely this ought to work.

If neither of these things work, then probably something has happened to the python installation that occurs when you install ArcMap.  The best thing to do is either to uninstall and reinstall ArcMap or to call [Esri Tech Support](http://support.esri.com/en/).

Let me know what you find out.

**Comment by j7hanson** [comment]
Neither work. I get a similar error.
ImportError: C extension: No module named builtins not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.

**Comment by mmorang** [comment]
Yep, time to call Tech Support.  Tell them that your python installation is messed up and that you can't import standard modules like pandas or sqlite3.

**Comment by j7hanson** [comment]
I'll try uninstall and reinstalling arcmap. Thanks

**Comment by mmorang** [comment]
Okay.  Good luck.  I'm going to close this issue, but feel free to open another one if you have further tool problems after getting your ArcMap working again.

**Comment by j7hanson** [comment]
I appreciate the help! Thanks, Melinda.
