### ISSUE TITLE
Unable to create on-street Routes because the Solve failed

### ISSUE THREAD

**Issue by proma90** [Esri/public-transit-tools#90]
Hi everyone,

i'm trying to generate shapes with network analysis, however, when I'm running the tool, it gave me these comments per each route:

> Unable to create on-street Routes because the Solve failed.
> Solve warning messages:
> Cannot use hierarchy when the hierarchy level count is zero.
> 
> Solve error messages:
> ERROR 030024: Solve returned a failure.
> Invalid context.
> Failed to execute (Solve).

Could anyone help me to solve this problem?
Thanks!

**Comment by mmorang** [comment]
This indicates a problem with the network dataset you're using.  Your network has a [hierarchy attribute](http://desktop.arcgis.com/en/arcmap/latest/extensions/network-analyst/understanding-network-attributes.htm#GUID-60C9FE9A-6472-49DE-B583-73DE491BEE9A), but it wasn't [set up properly](http://desktop.arcgis.com/en/arcmap/latest/extensions/network-analyst/network-analysis-with-hierarchy.htm).  If your network is purely a pedestrian network, then you don't need hierarchy anyway, and you should delete the hierarchy attribute, rebuild your network, and try again.

**Comment by mmorang** [comment]
If you're not certain of the quality of your network dataset, and you have an ArcGIS Online account with service credits, you can use the ArcGIS Online version of the tool to create on-street routes.

**Comment by proma90** [comment]
Thanks, I will check it.

**Comment by proma90** [comment]
Hi, I've used the ArcGis Online version and it draws straight lines...could you tell me where or how I can create/obtain a proper network dataset?
Thanks

**Comment by mmorang** [comment]
Does the ArcGIS Online version throw a warning message indicating why it produced straight lines?  It should not produce straight lines unless it was unable to successfully use the online routing service, and in that case, it should give a warning.  Perhaps if you tell me the warning, I can help get this tool working for you.

If you want to purchase a network dataset, you can purchase Esri's [Streetmap Premium](http://www.esri.com/data/streetmap) product for the geography you're interested in.  It contains high quality street data, including walking and pedestrian attributes, for much of the world.  The data is the same or similar as that used by the ArcGIS Online services.

If you want something free, you can create a network dataset using OpenStreetMap data.  The process is a bit arduous, and the OSM data itself often needs to be cleaned up a lot.  Quality varies depending on the location.  The [ArcGIS Editor for OpenStreetMap](http://www.esri.com/software/arcgis/extensions/openstreetmap) can help you out.

**Comment by mmorang** [comment]
Hello @proma90. Did you ever get this to work?
